#!/bin/sh /etc/rc.common

START=98

USE_PROCD=1
PROG=/usr/sbin/SmartCar

start_service() {
        procd_open_instance
        procd_set_param command $PROG --systemd
        procd_set_param stderr 1
        procd_close_instance
}

reload_service() {
        procd_send_signal $PROG
}
